### ISSUE TITLE
Grafana 7.5.5 support.

### ISSUE THREAD

**Issue by 0megam** [kentik/kentik-grafana-app#35]
Hi All,
Is kentik plugin supports grafana 7 ?
After install i'm getting some wierd errors like "can't update datasource" and  "dashboard not found".
Thanks.

**Comment by MegaH01** [comment]
Same here.  Plugin is broken in Grafana 8.x too

**Comment by dpajin-kentik** [comment]
The latest version of the plugin is supported in Grafana 7 and Grafana 8.
