### ISSUE TITLE
Autocomplete for plugin

### ISSUE THREAD

**Issue by jkowall** [kentik/kentik-grafana-app#4]
Is there a way to make the plugin auto-complete certain metadata? This comes from a customer request.

**Comment by jonyrock** [comment]
@jkowall I think it possible. prometheus has autocmplete. We can fetch data for completion or hardcode something. 

@jkowall can you give an example, please?

**Comment by jkowall** [comment]
Yes, the Kentik customer who asked about this said they have that feature on Prometheus and they would like Kentik to do the same thing. We could fetch the data for completion if possible. If you need some API directions I can ask our team. If you have an idea then I'm happy to see what you come up with. Thanks, Alex!

**Comment by rozetko** [comment]
Is autocompletion needed for Device / Unit / Metric fields in datasource config?
![image](https://user-images.githubusercontent.com/1989898/63420546-8c5d7780-c40f-11e9-9366-f6bab7eece4a.png)

**Comment by jkowall** [comment]
I don't think this is necessary for the config since this is not used too often. Correct me if I'm wrong.

**Comment by jonyrock** [comment]
We can also ad documentation like this:

![image](https://user-images.githubusercontent.com/1022757/63634657-3a606000-c662-11e9-86c2-f527290c3ac8.png)

**Comment by jkowall** [comment]
Docs would be good, I can help write and tune the language, just let me know

**Comment by amper43** [comment]
@jkowall 
Is autocompletion needed for filter's value?

![image](https://user-images.githubusercontent.com/5675912/63766257-764e2c00-c8d3-11e9-8efc-fad7a3949c74.png)

**Comment by jkowall** [comment]
Yes, I think that would be useful to the user, what do you think?

**Comment by jonyrock** [comment]
@jkowall let do it! We think it's cool

**Comment by jkowall** [comment]
Clarification the autocomplete is for Metric and Device (more is good too).

**Comment by jonyrock** [comment]
I think we can close this issue.
