### ISSUE TITLE
Resolve IPs in a given view

### ISSUE THREAD

**Issue by jkowall** [kentik/kentik-grafana-app#5]
Is there a way to resolve IPs within Grafana? Maybe allow the customer to specify a DNS server and resolve the IPs against it?

**Comment by jkowall** [comment]
If you have questions just let me know, thanks.

**Comment by rozetko** [comment]
There are 2 ways to achieve this:
- use [DNS over HTTPS](https://tools.ietf.org/html/rfc8484). It should be supported by a DNS server. Public DNS servers can be used if there is no need to support customers' servers.
- proxy queries from plugin to DNS servers in a backend app

**Comment by jkowall** [comment]
I think both options would be good

**Comment by corpglory-dev** [comment]
We are going to resolve DNS-name by IP in following parts of the dashboard: filter values, dashboard legend, IPs in table

![image](https://user-images.githubusercontent.com/5675912/64554058-4b3bf180-d343-11e9-893c-94aee16352c5.png)

Is it the expected places for IPs resolving?

**Comment by jkowall** [comment]
Yes, looked good, thanks!

**Comment by corpglory-dev** [comment]
There are limitations for DNS-resolving from browser, such as:
- DNS-server must support DNS over HTTPS;
- DNS-server must add valid CORS headers.
Not many public DNS-servers meet these requirements.

Looks like we have only one option: send a request to a backend service.

**Comment by jkowall** [comment]
So we cannot resolve the DNS on the backend, it needs to be done via the browser within Javascript code?

**Comment by jonyrock** [comment]
@jkowall we can't resolve it within javascript code. We need a backend app for this task

**Comment by jkowall** [comment]
Let me go back to the customer and provide an update and see what they prefer. Thanks.

**Comment by jonyrock** [comment]
just for protocol https://stackoverflow.com/questions/102605/can-i-perform-a-dns-lookup-hostname-to-ip-address-using-client-side-javascript

also it's strange that we can resolve to different IP on different machines. It's better to have "one source of truth".

Can Kentik server (API) do it?

**Comment by jkowall** [comment]
So I have good news, there is an undocumented flag for the API called hostnameLookup if you need more info on how to use it let me know and I can ask the developers.

**Comment by corpglory-dev** [comment]
We can add "DNS Lookup" option for enabling / disabling names resolving:
![image](https://user-images.githubusercontent.com/5675912/65604100-8844ec80-dfaf-11e9-83cd-10253da32984.png)

When "DNS Lookup" is enabled, user can see resolved names (if resolving is successful) instead of IPs (green rectangles):
![image](https://user-images.githubusercontent.com/5675912/65605163-52086c80-dfb1-11e9-88a3-80d58040963c.png)

**Comment by jonyrock** [comment]
We got approve to make "DNS Lookup" feature optional, so let's keep that template variable like you showed:
![image](https://user-images.githubusercontent.com/1022757/65704139-a7ff1200-e08e-11e9-894c-07ab7845d738.png)
