### ISSUE TITLE
API - Grafana plugin hitting 429's through device calls (UI-App #15855)

### ISSUE THREAD

**Issue by dkelly-kentik** [kentik/kentik-grafana-app#69]
**Reported Issue**
**Summary**
Grafana Plugin - Rate Limits/Errors/Slowness

**Description**
Grafana plugin is a somewhat painful experience. Default queries are returning 429 rate limit warnings/errors nearly each time a query is run. An example dashboard we've obtained partially loads, often times multiple 429 errors are present. Screenshots, logs and dashboard json attached. None of the queries appear to be anything too complex but maybe the amount of devices is causing the issue. It's not clear to me how the query is formed from grafana to kentik api.

**History**
/v4/profile (PUSH)
**Screen/Browser**
**Viewport**: 2525x1323

View Ticket in Zendesk: [#700](https://kentik.zendesk.com/agent/tickets/700)

**Comment by dkelly-kentik** [comment]
https://github.com/kentik/ui-app/issues/15855   Sourced from UI App issue here.

**Comment by dkelly-kentik** [comment]
Daniel Kelly commented ([#700](https://kentik.zendesk.com/agent/tickets/700)):

![image](https://user-images.githubusercontent.com/35575466/214096150-f626a2cd-8032-4403-ba6c-643e362acadb.png)
![image](https://user-images.githubusercontent.com/35575466/214096217-b9659f8f-e4a1-41bf-b325-ba6c76462f33.png)

**Comment by dkelly-kentik** [comment]
It is the number of devices they have - that is what is causing the issue here.

**Comment by dkelly-kentik** [comment]
@nickstinemates I think you are the correct resource to bring this to, please let me know if that is not so!

**Comment by lrhildebrand** [comment]
This continues to be an issue for Tesla.  I think this is important that we get this looked at.  Any recommendations?
![image](https://user-images.githubusercontent.com/92396142/221648089-0e717efc-59f6-4c7b-b26c-47f2f36d5389.png)

**Comment by silvgeb** [comment]
https://github.com/kentik/ui-app/issues/15855

**Comment by silvgeb** [comment]
Copying over comment by @mmac-m3a from the original ticket:

> Considering that the plugin is our software, maybe we can alleviate the problem by making the plugin retry after 429 responses from Kentik API (as well behaved REST clients should). Based on my reading of the code, it would require to wrap the Grafana "backend server" (imported [here](https://github.com/kentik/kentik-grafana-app/blob/6bb7d1f3c1049463a661fe6f7ce4fea788e4eacd/src/config/config.ts#L6) in the plugin) do the retry. AFAICT, the [Grafana runtime code](https://github.com/grafana/grafana/blob/main/packages/grafana-runtime/src/services/backendSrv.ts) uses generic [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), which does not do retries by default and AFAICT has no option to enable them, so we'd need to wrap it. There are NPM modules (e.g. [p-retry](https://github.com/sindresorhus/p-retry)) that should enable that, however I've not found any module that would do the whole thing, i.e. parse headers in the 429 response and wait the required interval.

**Comment by dpajin-kentik** [comment]
@dkelly-kentik @silvgeb @lrhildebrand we have a fix for this, we still need to make a package available on Grafana Cloud, I hope it will be ready in next few days... I will let you know

**Comment by silvgeb** [comment]
hi @dpajin-kentik , any update on the fix? has it been deployed?

**Comment by dpajin-kentik** [comment]
Hi @silvgeb, there is a new release v1.6.2 which includes the fix and the package is available here https://github.com/kentik/kentik-grafana-app/releases
It can be manually installed, but it still not available on Grafana Cloud, it is waiting for approval by Grafana... it takes couple of days to be processed and approved (I hope)

**Comment by silvgeb** [comment]
Thank you! Please let us know once it's available on Grafana Cloud.

**Comment by dpajin-kentik** [comment]
@silvgeb, Kentik Grafana App v1.6.2 is now available on Grafana Cloud and it contains the fix for this issue. 
I will close the issue here, please feel free to re-open in case there is a need. Thanks!

**Comment by silvgeb** [comment]
Thank you!!
